
let handler = m => m
handler.all = async function (m) {
  for (const message in audioMsg) {
    if (new RegExp(`^${message}$`, 'i').test(m.text)) {
      this.sendFile(m.chat, audioMsg[message], 'audio.mp3', null, m, true)
      break
    }
  }
  return !0
 }

export default handler


let audioMsg = {
  'fino señores': './src/mp3/fino.mp3",
  'alive' : 'https://i.imgur.com/iUOGcyF.mp3',
'poda':'https://i.imgur.com/e2PKT60.mp3',
'lyfe':'https://i.imgur.com/73QMUoC.mp3',
'sed':'https://i.imgur.com/B71ASsj.mp3',
'raganork' : 'https://i.imgur.com/u5Pp11A.mp3',
'bot' : 'https://i.imgur.com/dqgoyna.mp3',
'hi' : 'https://i.imgur.com/6mjEiA6.mp3', 
'hey':'https://i.imgur.com/2AbxJCd.mp3', 
'pavam':'https://i.imgur.com/kYzbJbx.mp3', 
'admin':'https://i.imgur.com/DVuOkgD.mp3', 
'ok':'https://i.imgur.com/5lniXiJ.mp3', 
'nirthipoda':'https://i.imgur.com/c6wEqlx.mp3', 
'sad':'https://i.imgur.com/5NZDe8m.mp3', 
'eda':'https://i.imgur.com/iaHKsGW.mp3', 
'tag':'https://i.imgur.com/NGWrUkQ.mp3', 
'umma':'https://i.imgur.com/GUtD1hr.mp3', 
'velachil':'https://i.imgur.com/PBuALN3.mp3', 
'gold':'https://i.imgur.com/79YoX98.mp3', 
'pavam':'https://i.imgur.com/Cjd55is.mp3', 
'arada':'https://i.imgur.com/HzIz3ls.mp3', 
'para':'https://i.imgur.com/2jzZauR.mp3', 
'phub':'https://i.imgur.com/oKVVwIj.mp3', 
'fan':'https://i.imgur.com/AzqHkeV.mp3', 
'duet':'https://i.imgur.com/pf1BWXN.mp3', 
'aa':'https://i.imgur.com/N2N6S7C.mp3', 
'thanks':'https://i.imgur.com/IrEdvwL.mp3', 
'kozhi':'https://i.imgur.com/4fdJUoj.mp3', 
'umfi':'https://i.imgur.com/FaOtaF5.mp3', 
'who':'https://i.imgur.com/wsrdnP8.mp3', 
'vaa':'https://i.imgur.com/imr3bC8.mp3', 
'sheri':'https://i.imgur.com/Xgzkbsk.mp3', 
'pedi':'https://i.imgur.com/0WML13D.mp3', 
'nannayi':'https://i.imgur.com/b491tUX.mp3', 
'kundan':'https://i.imgur.com/GuAnUuf.mp3', 
'killadi':'https://i.imgur.com/yVwoqYp.mp3', 
'bhai':'https://i.imgur.com/WgMgTBP.mp3', 
'kk':'https://i.imgur.com/LQBlI1y.mp3', 
'hy':'https://i.imgur.com/EQn2BvM.mp3', 
'violence':'https://i.imgur.com/SIj26aP.mp3', 
'suii':'https://i.imgur.com/IWlTmTE.mp3', 
'single':'https://i.imgur.com/c4E7E1k.mp3', 
'Mass':'https://i.imgur.com/D5PREWe.mp3', 
'Chunk':'https://i.imgur.com/JL6FWpS.mp3', 
'Ooi':'https://i.imgur.com/rvD8PlZ.mp3', 
'Haha':'https://i.imgur.com/ChUKdPk.mp3', 
'Jao':'https://i.imgur.com/z9oQd4N.mp3', 
'Beeshma':'https://i.imgur.com/z9oQd4N.mp3', 
'Kalipan':'https://i.imgur.com/vkdcGHu.mp3', 
'Ettayi':'https://i.imgur.com/vkdcGHu.mp3', 
'Mothalali':'https://i.imgur.com/K2QlmTc.mp3', 
'Kaliyakunne':'https://i.imgur.com/AeGNKo3.mp3', 
'Nenben':'https://i.imgur.com/Qe5khtL.mp3', 
'Cr7':'https://i.imgur.com/lCZl3Af.mp3', 
'Ethokke':'https://i.imgur.com/AsEfT76.mp3', 
'Sheri enna':'https://i.imgur.com/KraBTPf.mp3', 
'Gangster':'https://i.imgur.com/fbvDI1g.mp3', 
'Idiot':'https://i.imgur.com/uazVUOH.mp3', 
'Ff':'https://i.imgur.com/YN04ot5.mp3', 
'ff':'https://i.imgur.com/YN04ot5.mp3', 
'Free fire':'https://i.imgur.com/YN04ot5.mp3', 
'Hlo':'https://i.imgur.com/tZFBfRR.mp3', 
'Helo':'https://i.imgur.com/P9ntmn3.mp3', 
'Big fan':'https://i.imgur.com/5My5AdW.mp3', 
'Myre':'https://i.imgur.com/kGBtBXV.mp3', 
'Endi':'https://i.imgur.com/2nzjJPc.mp3', 
'Perfect ok':'https://i.imgur.com/z2JJQFh.mp3', 
'Ooi':'https://i.imgur.com/kjUcXHD.mp3', 
'Arum ille':'https://i.imgur.com/67wdgg4.mp3', 
'Njan vanne':'https://i.imgur.com/BYx4Q0t.mp3', 
'Kooi':'https://i.imgur.com/NIrmfFy.mp3', 
'Ne oru killadi thanne':'https://i.imgur.com/AlUiq7V.mp3', 
'Killadi':'https://i.imgur.com/AlUiq7V.mp3', 
'Ara':'https://i.imgur.com/2pBlu1Z.mp3', 
'Hacker':'https://i.imgur.com/wF8xr4k.mp3', 
'Hecker':'https://i.imgur.com/wF8xr4k.mp3', 
'Ayo ayo':'https://i.imgur.com/wF8xr4k.mp3',
'mwonu':'https://i.imgur.com/fkmoBaC.mp3'
}
